name: Pylint

on:
  pull_request:
    paths:
      - .github/**
      - .devcontainer/**
      - pynet/**
      - pyproject.toml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
