name: Tests

on:
  pull_request:
    paths:
      - .github/**
      - .devcontainer/**
      - pynet/**
      - pyproject.toml

jobs:
  unit-test-model:
    runs-on: ubuntu-latest
    container: tensorflow/tensorflow:2.11.0
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U pip
          pip install -e ".[dev]"
          python -m pytest -s pynet/tests/test_pynet.py
  unit-test-losses:
    runs-on: ubuntu-latest
    container: tensorflow/tensorflow
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U pip
          pip install -e ".[dev]"
          python -m pytest -s pynet/tests/test_losses.py
